# Generated by Django 5.2.6 on 2025-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (0 = sin descuento)'),
        ),
    ]
