# Generated by Django 5.2.6 on 2025-09-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
