# Generated by Django 5.2.6 on 2025-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='datos_usuarios',
        ),
    ]
